import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import { FooterModule, HeaderModule } from '@/modules/layout'
import { ThemeProvider } from '@/providers'
import { cn } from '@/utils'
import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('bg-background font-sans antialiased', fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <div className="container flex flex-col justify-between h-screen py-8 px-20">
            <header className="sticky top-0 z-10">
              <HeaderModule />
            </header>
            <main className="flex-1 flex items-center justify-center h-full">{children}</main>
            <footer>
              <FooterModule />
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
