export enum ERROR_TYPES {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  REGISTRATION_PROBLEM = 'REGISTRATION_PROBLEM',
  LOGIN_PROBLEM = 'LOGIN_PROBLEM',
}
